FROM node:18 AS builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./
COPY next-env.d.ts ./
COPY next.config.js ./
COPY next.config.mjs ./
COPY tsconfig.json ./

RUN npm install --force

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Run the built code
FROM node:18

WORKDIR /app

COPY --from=builder /app/ ./

EXPOSE 3000

CMD ["npm", "start"]
